kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations:
    kubernetes.io/service-account.name: build-robot
type: kubernetes.io/service-account-token
EOF


---

apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: app
    resourceVersion: "1846"
    uid: 29617d7f-726c-4dea-953a-85ae97c96b18
  secrets:
  - name: default-token-bxz76
